version: '3.1'

services:
    php:
        image: ambientum/php:7.3
        container_name: leadlovers-php
        environment:
            - XDEBUG_ENABLED=true
        volumes:
            - .:/var/www/app
            - ./nginx/99_overrides.ini:/etc/php7/conf.d/99_overrides.ini
            - ./nginx/99_xdebug.ini:/etc/php7/conf.d/99_xdebug.ini
        command: ['tail', '-f', '/dev/null']