version: '3.1'

services:
    php:
        image: ambientum/php:7.3
        container_name: leadlovers-php
        environment:
            - XDEBUG_ENABLED=true
        volumes:
            - .:/var/www/app
        command: ['tail', '-f', '/dev/null']